# Generated by Django 5.2.2 on 2025-06-05 01:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=8, null=True)),
                ('page', models.CharField(choices=[('index', 'Index'), ('si', 'SI'), ('isi', 'ISI'), ('details', 'Details')], max_length=20)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
